exp_name: ex_data/suta_base_0725
topk: 30
train_params: [feature, LN] # currently supported: all, feature, LN, ...
steps: 15
asr: tiny
train_feature: true
encoderLN: true
decoderLN: true
### optimizer & train hyparameters & learning rate scheduler
opt: AdamW
episodic: true # load pretrained model again for every batch
temp: 2.5 # temperature scaling
em_coef: 0.5 # for balancing entropy minimization and minimum class confusion for baseline
p_ratio: 1
lr: 1e-3
scheduler: null # null or CosineAnnealingLR
t_max: 10
lr_min: 1e-3
### dataset
noise_type: null # currently supported: null, AirConditioner_6, AirportAnnouncements_2, Babble_4, CopyMachine_2, Munching_3, Neighbor_6, ShuttingDoor_6, Typing_2
dataset_name: librispeech
dataset_dir: ../TTA_LAS/test

extra_noise: 0.00
noise_snr: 10
sample_rate: 16000
batch_size: 1

### device
device: cuda

### seed for reproductivity
seed: 42
