python main.py  --steps 10 \
                --asr tiny \
                --task translation \
                --lang pt \
                --dataset_name covost2 \
                --dataset_dir ../covost2_pt \
                --temp 2.5 \
                --episodic \
                --non_blank \
                --em_coef 0.3 \
                --reweight \
                --log_dir exps \
                --lr 2e-5 \
                --is_whisper \
                --train_feature \
                --encoderLN \
                --decoderLN \
                --topk 30 \
                --beam_size 0