python main.py  --steps 10 \
                --asr tiny \
                --dataset_name aishell3 \
                --dataset_dir  ./aishell_test \
                --temp 2.5 \
                --episodic \
                --non_blank \
                --em_coef 0.3 \
                --reweight \
                --log_dir exps \
                --lr 2e-5 \
                --topk 30 \
                --train_feature \
                --extra_noise 0. \
                --is_whisper \
                --decoderOnly \
                --beam_size 0