python main.py  --steps 10 \
                --asr tiny.en \
                --dataset_name librispeech \
                --dataset_dir  ./LibriSpeech \
                --temp 2.5 \
                --episodic \
                --non_blank \
                --em_coef 0.3 \
                --reweight \
                --log_dir exps \
                --lr 2e-5 \
                --topk 30 \
                --train_feature \
                --extra_noise 0.01 \
                --is_whisper True \
                --encoderOnly False \
                --decoderOnly True \
                --beam_size 0